# escape=`

FROM mcr.microsoft.com/powershell:7.1.2-ubuntu-20.04

# Set default directory to C:\Agent
WORKDIR /agent

# Set PowerShell as default shell
SHELL [ "pwsh", "-NoProfile", "-Command" ]

# Install VSTS/DevOps self-hosted Agent
ARG agentversion=2.214.1
ENV agentversion=${agentversion}
ENV AGENT_ALLOW_RUNASROOT 1
RUN $ProgressPreference = 'SilentlyContinue' ; `
    Invoke-WebRequest -Uri "https://vstsagentpackage.azureedge.net/agent/$env:agentversion/vsts-agent-linux-x64-$env:agentversion.tar.gz" -OutFile "./vsts-agent-linux-x64-$env:agentversion.tar.gz" -UseBasicParsing ; `
    tar  zxvf "./vsts-agent-linux-x64-$env:agentversion.tar.gz" ; `
    rm "./vsts-agent-linux-x64-$env:agentversion.tar.gz" ; `
    ./bin/installdependencies.sh 

# Download the Microsoft repository GPG keys
RUN Invoke-WebRequest -Uri https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -OutFile ./packages-microsoft-prod.deb -UseBasicParsing ; `
  # Register the Microsoft repository GPG keys
  dpkg -i ./packages-microsoft-prod.deb ; `
  rm ./packages-microsoft-prod.deb

# Install PS Modules in C:\Modules
RUN Install-Module Az -Force -Scope AllUsers ; `
    Install-Module Pester -Force -Scope AllUsers ; `
    Install-Module PSScriptAnalyzer -Force -Scope AllUsers

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash ; `
    rm -rf /var/lib/apt/lists/*

RUN apt install git -y ; `
    apt-get install apt-transport-https -y ; `
    apt-get update ; `
    apt-get install apt-utils ; `
    apt-get install ca-certificates ; `
    apt-get install curl ; `
    apt-get install iputils-ping ; `
    apt-get install jq ; `
    apt-get install lsb-release ; `
    apt-get install software-properties-common ; `
    apt-get install zip ; `
    apt-get install unzip

ENTRYPOINT [ "/bin/bash", "-c", "./config.sh --unattended --replace && ./run.sh" ]
