trigger: none

schedules:
- cron: "30 21 * * Mon-Fri" # First number represent the amount of minutes, second represent the hours. In this case 21:30 Monday - Friday
  displayName: Stop Self Hosted Agent Container
  branches:
    include: 
    - master
  always: true

pool:
  vmImage: 'windows-latest'

variables:
  ResourceGroupName: 'rg-networking'
  ACIname: 'polarisbuildagentprod'
  ServiceConnection: 'Innovation-Production: All-Information Management'

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# =-=                                               DON't CHANGE ANYTHING BELOW THIS LINE!!                                                     =-=
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(ServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: './powershell-scripts/StopContainer.ps1'
    ScriptArguments: '-ResourceGroupName $(ResourceGroupName) -ResourceName $(ACIname)'
    azurePowerShellVersion: 'LatestVersion'
